namespace Number
{
    internal class Program
    {
        static void Main(string[] args)
        {
        

            Console.WriteLine("Welcome! You need to guess the number generated by the program.");

            int lowerBound = 0, upperBound = 0;
            bool isValidRange = false;

            // Get valid range
            while (!isValidRange)
            {
                Console.Write("Enter the lower bound: ");
                if (!int.TryParse(Console.ReadLine(), out lowerBound))
                {
                    Console.WriteLine("Please enter a valid integer for the lower bound.");
                    continue;
                }

                Console.Write("Enter the upper bound: ");
                if (!int.TryParse(Console.ReadLine(), out upperBound))
                {
                    Console.WriteLine("Please enter a valid integer for the upper bound.");
                    continue;
                }

                if (lowerBound >= upperBound)
                {
                    Console.WriteLine("The lower bound must be less than the upper bound. Please try again.");
                }
                else
                {
                    isValidRange = true;
                }
            }

            // Generate random number
            Random random = new Random();
            int randomNumber = random.Next(lowerBound, upperBound + 1);
            int attempts = 0;
            const int maxAttempts = 5;  // Set maximum attempts to 5
            bool isGuessed = false;

            Console.WriteLine($"\nThe program has generated a number between {lowerBound} and {upperBound}.");
            Console.WriteLine($"You have {maxAttempts} attempts to guess the correct number.");

            // Guessing loop
            while (!isGuessed && attempts < maxAttempts)
            {
                Console.Write("Enter your guess: ");
                int userGuess;

                // Input validation
                if (int.TryParse(Console.ReadLine(), out userGuess))
                {
                    // Validate if the guess is within the range
                    if (userGuess < lowerBound || userGuess > upperBound)
                    {
                        Console.WriteLine($"Please enter a number between {lowerBound} and {upperBound}.");
                        continue;
                    }

                    attempts++;

                    if (userGuess < randomNumber)
                    {
                        Console.WriteLine("Try a higher number.");
                    }
                    else if (userGuess > randomNumber)
                    {
                        Console.WriteLine("Try a lower number.");
                    }
                    else
                    {
                        isGuessed = true;
                        Console.WriteLine($"\nCongratulations! You guessed the number {randomNumber}.");
                        Console.WriteLine($"It took you {attempts} attempts.");
                    }
                }
                else
                {
                    Console.WriteLine("Please enter a valid integer.");
                }

                // Check if the user has exceeded the maximum attempts
                if (attempts >= maxAttempts && !isGuessed)
                {
                    Console.WriteLine($"\nSorry, you've exceeded the maximum number of attempts. The correct number was {randomNumber}.");
                    break;
                }
            }

            Console.WriteLine("Game over. Thanks for playing!");
        }
    }
}
